### ISSUE TITLE
Unable to start activity 

### ISSUE THREAD

**Issue by JonathanImperato** [PaoloRotolo/GittyReporter#6]
java.lang.RuntimeException: Unable to start activity ComponentInfo{signature.Gitty}: android.view.InflateException: Binary XML file line #175: Error inflating class com.melnykov.fab.FloatingActionButton
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$900(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
     Caused by: android.view.InflateException: Binary XML file line #175: Error inflating class com.melnykov.fab.FloatingActionButton
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)

at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.github.paolorotolo.gitty_reporter.GittyReporter.onCreate(GittyReporter.java:51)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$900(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.github.paolorotolo.gitty_reporter.GittyReporter.onCreate(GittyReporter.java:51)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$900(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
     Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 18
            at android.content.res.TypedArray.getColor(TypedArray.java:401)
            at com.melnykov.fab.FloatingActionButton.initAttributes(FloatingActionButton.java:112)
            at com.melnykov.fab.FloatingActionButton.init(FloatingActionButton.java:103)
            at com.melnykov.fab.FloatingActionButton.<init>(FloatingActionButton.java:72)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.github.paolorotolo.gitty_reporter.GittyReporter.onCreate(GittyReporter.java:51)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$900(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

Why i get this message?

**Comment by JonathanImperato** [comment]
So, no answer?

**Comment by paolorotolo** [comment]
@Heromine can you please share your project on GitHub? I'll have a look.

**Comment by JonathanImperato** [comment]
@PaoloRotolo Main: https://github.com/Heromine/tempapp1/blob/master/MainActivity.java
Gitty: https://github.com/Heromine/tempapp1/blob/master/Gitty.java

**Comment by paolorotolo** [comment]
@Heromine I'm afraid I need your res/ folder and gradle files too. :)

**Comment by JonathanImperato** [comment]
@PaoloRotolo Gradle:https://github.com/Heromine/tempapp1/blob/master/build.gradle
res zip: https://github.com/Heromine/tempapp1/blob/master/res.zip

**Comment by paolorotolo** [comment]
@Heromine sorry, I can't still find the bug :( Can you please share with me the whole project? I'll import it in my Android Studio.

**Comment by JonathanImperato** [comment]
@PaoloRotolo I'll give you the whole project  
as soon as possible

**Comment by paolorotolo** [comment]
@Heromine thanks!

**Comment by JonathanImperato** [comment]
@PaoloRotolo Ok, here you are. app.zip: https://github.com/Heromine/tempapp1/blob/master/app.zip

**Comment by paolorotolo** [comment]
@Heromine I've just released v. 1.1.1. It should fix your issue :)

**Comment by JonathanImperato** [comment]
@PaoloRotolo what was the issue?

**Comment by paolorotolo** [comment]
@Heromine Id conflict in xml files.

**Comment by paolorotolo** [comment]
Also remember to `return true` after intent.

```
            case R.id.action_bug:
                Intent intent = new Intent(this, Gitty.class);
                startActivity(intent);
                return true;
```

**Comment by JonathanImperato** [comment]
@PaoloRotolo thank you a lot

**Comment by paolorotolo** [comment]
@Heromine np, let me know if it works now.

**Comment by Heromine** [comment]
@PaoloRotolo it says there is no 1.1.1 version

**Comment by JonathanImperato** [comment]
@PaoloRotolo works fine, thank you.

**Comment by paolorotolo** [comment]
Good! Closing.
